### PR TITLE
Fix Results Panel not Refreshing Automatically

### LINKED ISSUE #669: Results Panel not Refreshing Automatically
- MSSQL Extension Version: 0.2.0
- VSCode Version: 1.9.0
- OS Version: Windows 10

Just upgraded to stable version 1.9.0 and noticed that the results panel does not refresh automatically every time I run the query. It used to work fine with the previous version of VSCode.

Steps to Reproduce:

1. Execute a query
2. Modify the query and run again, the results pane will not automatically refresh with the results for the modified query.

### PR DESCRIPTION
**Pull request by kevcunnane**
- Fixes #669
- Ensures that TextDocumentContentProvider.provideTextDocumentContent always provides an updated string when being refreshed. In VSCode 1.9.0, it's vital to do this as there is a diff on the provided content and the document is only refreshed if this is different

### CODE REVIEW

File: src/models/SqlOutputContentProvider.ts [hunk 1]
```diff
@@ -411,13 +411,13 @@ export class SqlOutputContentProvider implements vscode.TextDocumentContentProvi
     public provideTextDocumentContent(uri: vscode.Uri): string {
         // URI needs to be encoded as a component for proper inclusion in a url
         let encodedUri = encodeURIComponent(uri.toString());
-
-        // return dummy html content that redirects to 'http://localhost:<port>' after the page loads
+        let timeNow = new Date().getTime();
```
Comment (anthonydresser) [inline src/models/SqlOutputContentProvider.ts]: Might be good to add a comment referencing a github issue to know why this was done in the future when everyone has forgotten about this problem.

Comment (kevcunnane) [inline src/models/SqlOutputContentProvider.ts]: Good point - updated in latest commit
