### PR TITLE
Fix font settings

### LINKED ISSUE #18351: New Query Results pane does not follow existing font size and font family settings
> the new pane does not seem to respect the following settings:
> mssql.resultsFontFamily
> mssql.resultsFontSize
> 
> Thank you for pointing me in the right direction. 

 _Originally posted by @gwduvalljr-AT in [#1553](https://github.com/microsoft/vscode-mssql/issues/1553#issuecomment-2453482551)_

### PR DESCRIPTION
**Pull request by cssuh**
Make default font family & font size = null, and adjust cell size accordingly for larger font sizes.

Example - font size 20:
Screenshot 2025-01-06 at 4 05 14 PM

Fixes #18351

### CODE REVIEW

**Comment by lewis-sanchez** [comment]
Could you attach screenshots of the results pane respecting font family and font size settings?

**Review by kburtram — APPROVED** [review]

**Comment by cssuh** [comment]
This still needs some tweaking for font sizes 25 & up, will adjust this before I merge.

File: src/reactviews/pages/QueryResult/queryResultPane.tsx [hunk 1]
```diff
@@ -236,6 +234,7 @@ export const QueryResultPane = () => {
         gridCount: number,
     ) => {
         const divId = `grid-parent-${batchId}-${resultId}`;
+        console.log(metadata.fontSettings.fontSize ?? 12);
```
Comment (Benjin) [inline src/reactviews/pages/QueryResult/queryResultPane.tsx:237]: Remove

**Review by Benjin — APPROVED** [review]
