### PR TITLE
Fix copy bug by adding null check

### LINKED ISSUE #596: Cannot copy from results grid if selection contains null
Steps to Reproduce:
1. Run a query that will have null values in the resultset 
2. Make a selection in the grid that includes null values

Expected Behavior:
All values are copied to clipboard, including the null values

Actual Behavior:
Nothing is copied to the clipboard. 

Copyable:
image

Uncopyable:
image

### PR DESCRIPTION
**Pull request by coquagli**
Fixes #596. Note that the value in `row` comes back as `null` and not `undefined` for `null` data.

### CODE REVIEW

File: src/controllers/QueryRunner.ts [hunk 1]
```diff
@@ -295,7 +295,7 @@ export default class QueryRunner {
                         for (let row of result.resultSubset.rows) {
                             // iterate over the cells we want from that row
                             for (let cell = range.fromCell; cell <= range.toCell; cell++) {
-                                if (self.shouldRemoveNewLines() && row[cell]) {
+                                if (row[cell] && self.shouldRemoveNewLines()) {
```
Comment (abist) [inline src/controllers/QueryRunner.ts]: shouldn't we check for null explicitly?

Comment (coquagli) [inline src/controllers/QueryRunner.ts]: I am not sure. This works currently, but JavaScript as some subtleties to it that might matter for things like this.

Comment (abist) [inline src/controllers/QueryRunner.ts]: you're right
http://stackoverflow.com/questions/5515310/is-there-a-standard-function-to-check-for-null-undefined-or-blank-variables-in
