### PR TITLE
Fixing always encrypted column results for AKV keys. 

### LINKED ISSUE #1656: Always Encrypted seems to not work properly.
- MSSQL Extension Version: 1.90
- VSCode Version: 1.43.2 (user setup)
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:
1. Create a connection where the connectionString uses `Column Encryption Setting=Enabled`.
2. Execute a query against a table which has an encrypted column.

``` TSQL
USE SampleDatabase
GO

SELECT * FROM TableWithEncryptedColumn
```

> [8:02:17 PM]	Started executing query at Line 1
> 	Commands completed successfully. 
> [8:02:17 PM]	Started executing query at Line 3
> 	(3 rows affected) 
> 	Query was canceled by user 
> 	Total execution time: 00:00:00.053
> 

<hr>

Just for clarity, if I remove the `Column Encryption Setting=Enabled` portion from the connection string and execute the same query, I get results back, with the encrypted columns remaining encrypted.

> [10:24:17 AM]	Started executing query at Line 1
> 	Commands completed successfully. 
> [10:24:17 AM]	Started executing query at Line 3
> 	(3 rows affected) 
> 	Total execution time: 00:00:00.055
>

### PR DESCRIPTION
**Pull request by aasimkhan30**
# Pull Request Template – vscode-mssql

## Description

This PR fixes #1656

## Code Changes Checklist

- [ ] New or updated **unit tests** added
- [ ] All existing tests pass (`npm run test`)
- [ ] Code follows [contributing guidelines](https://github.com/microsoft/vscode-mssql/blob/main/CONTRIBUTING.md)
- [ ] Telemetry/logging updated if relevant
- [ ] No regressions or UX breakage

### CODE REVIEW

File: src/controllers/connectionManager.ts [hunk 1]
```diff
@@ -117,6 +117,7 @@ export default class ConnectionManager {
         this._onConnectionsChangedEmitter.event;
 
     public initialized: Deferred<void> = new Deferred<void>();
+    private _keyVaultTokenCache: Map<string, IToken> = new Map<string, IToken>();
```
Comment (Benjin) [inline src/controllers/connectionManager.ts]: Can you add some unit tests that cover this request and the caching behavior?

**Review by Benjin — APPROVED** [review]
