### PR TITLE
Fixing code drawer styling in Schema Designer.

### LINKED ISSUE #19115: Change wording from "View Code" to "View Definition"
We have received multiple pieces of user feedback indicating that the wording "View Code" is confusing. The term "Definition" is more intuitive and also aligns with market standards.

Two locations that have "View Code": 
- Ribbon
- The expanded tab at the bottom with DDL statements.

(cc. @croblesm )

### LINKED ISSUE #19119: "Delete" and "Filter" buttons in Ribbon are not entirely clickable
Steps to Reproduce:
1. Hover over "Delete" and "Filter" button in the ribbon
2. Observe that only 1/3 of the button is clickable, whereas the rest is not

- Above the red line: Not clickable
- Under the red line: Clickable

Image

https://github.com/user-attachments/assets/b6549958-fde5-4b9b-84db-5942f6a5772d

### LINKED ISSUE #19124: "View Code" pane is not resizable
You cannot drag and resize the View Code pane, unlike the table designer.

https://github.com/user-attachments/assets/4570717b-818e-48cd-80ad-03d450bb0d50

### PR DESCRIPTION
**Pull request by aasimkhan30**
This PR fixes a few things

1. Streamlined the design by compacting the header. 
2. Made the panel resizable (Added a new library react-resizable-panels to achieve it with less code). Fixes  #19124
3. Added maximize, minimize button 
4. Changed the name of the panel from "View Code" to Definition Fixes #19115
5. Fixed the toolbar button not clickable issue  (It was caused as the `Find` widget was not properly hidden making the toolbar buttons not accessible. Fixes #19119
Now:
6. Added confirmations before some essential actions like Auto Arrange nodes and on node/edges deletion.

Now: 

https://github.com/user-attachments/assets/ef2f47ed-78d0-4437-a8b0-9551317db14d

image
image

Before:
image

### CODE REVIEW

File: src/reactviews/pages/SchemaDesigner/toolbar/schemaDesignerToolbar.tsx [hunk 1]
```diff
@@ -15,25 +15,27 @@ import { UndoRedoButtons } from "./undoRedoButton";
...
-            <ExportDiagramButton />
-            <ToolbarDivider />
-            <AddTableButton />
-            <UndoRedoButtons />
-            <AutoArrangeButton />
-            <DeleteNodesButton />
-            <ToolbarDivider />
-            <FilterTablesButton />
-        </Toolbar>
+        <div style={{ width: "100%", height: "30px", padding: "5px 0px" }}>
```
Comment (aasimkhan30) [inline src/reactviews/pages/SchemaDesigner/toolbar/schemaDesignerToolbar.tsx:18]: Making the dimensions of the toolbar fixed. This contributed to the problems of toolbars buttons not being clickable.

File: src/reactviews/pages/SchemaDesigner/toolbar/publishChangesDialogButton.tsx [hunk 2]
```diff
@@ -79,10 +78,11 @@ export function PublishChangesDialogButton() {
      */
     const triggerButton = () => {
         return (
-            <ToolbarButton
+            <Button
```
Comment (aasimkhan30) [inline src/reactviews/pages/SchemaDesigner/toolbar/publishChangesDialogButton.tsx:81]: Converting toolbar buttons to button to make them small. Haven't noticed any degradation of keyboard accessibility.

File: src/reactviews/pages/SchemaDesigner/toolbar/autoArrangeButton.tsx [hunk 3]
```diff
@@ -16,26 +25,52 @@ import eventBus from "../schemaDesignerEvents";
...
-                );
-                const generateComponenets = flowUtils.generateSchemaDesignerFlowComponents(schema);
-                reactFlow.setNodes(generateComponenets.nodes);
-                reactFlow.setEdges(generateComponenets.edges);
-            }}
-            title={locConstants.schemaDesigner.autoArrange}
-            appearance="subtle">
-            {locConstants.schemaDesigner.autoArrange}
-        </ToolbarButton>
+        <Dialog>
```
Comment (aasimkhan30) [inline src/reactviews/pages/SchemaDesigner/toolbar/autoArrangeButton.tsx:44]: Adding confirmation to auto arrange as users will lose their previous layout.

File: src/reactviews/pages/SchemaDesigner/schemaDesignerPage.tsx [hunk 4]
```diff
@@ -8,14 +8,22 @@ import { SchemaDesignerContext } from "./schemaDesignerStateProvider";
...
 import { SchemaDesignerToolbar } from "./toolbar/schemaDesignerToolbar";
 import { SchemaDesignerEditorDrawer } from "./editor/schemaDesignerEditorDrawer";
-import { SchemaDesignerCodeDrawer } from "./schemaDesignerCodeDrawer";
+import { SchemaDesignerDefinitionsPanel } from "./schemaDesignerDefinitionsPanel";
 import { SchemaDesignerFlow } from "./graph/SchemaDiagramFlow";
 import { SchemaDesignerFindTableWidget } from "./schemaDesignerFindTables";
-import { Spinner } from "@fluentui/react-components";
+import { makeStyles, Spinner } from "@fluentui/react-components";
 import { locConstants } from "../../common/locConstants";
+import { Panel, PanelGroup, PanelResizeHandle } from "react-resizable-panels";
```
Comment (aasimkhan30) [inline src/reactviews/pages/SchemaDesigner/schemaDesignerPage.tsx:16]: Introducing react-resizable-panels to reduce the code for making resizable panels.

File: src/reactviews/pages/SchemaDesigner/toolbar/undoRedoButton.tsx [hunk 5]
```diff
@@ -23,26 +23,28 @@ export function UndoRedoButtons() {
...
+                size="small"
+                appearance="subtle"
                 icon={<FluentIcons.ArrowRedo16Regular />}
                 onClick={() => {
                     eventBus.emit("redo");
                 }}
                 disabled={!isRedoEnabled}
-                title={"Redo"}
-                appearance="subtle">
+                title={"Redo"}>
```
Comment (lewis-sanchez) [inline src/reactviews/pages/SchemaDesigner/toolbar/undoRedoButton.tsx:45]: Did you forget to localize this since HTML titles are user facing?

File: src/reactviews/pages/SchemaDesigner/toolbar/undoRedoButton.tsx [hunk 6]
```diff
@@ -23,26 +23,28 @@ export function UndoRedoButtons() {
...
+                size="small"
+                appearance="subtle"
                 icon={<FluentIcons.ArrowUndo16Regular />}
                 onClick={() => {
                     eventBus.emit("undo");
                 }}
                 disabled={!isUndoEnabled}
-                title={"Undo"}
-                appearance="subtle">
+                title={"Undo"}>
```
Comment (lewis-sanchez) [inline src/reactviews/pages/SchemaDesigner/toolbar/undoRedoButton.tsx:34]: Localize this one too for consistency, if you forgot to localize this.

**Review by lewis-sanchez — APPROVED** [review]

File: src/reactviews/pages/SchemaDesigner/graph/SchemaDiagramFlow.tsx [hunk 7]
```diff
@@ -230,12 +253,59 @@ export const SchemaDesignerFlow = () => {
...
+                    <DialogBody>
+                        <DialogTitle>{locConstants.schemaDesigner.deleteConfirmation}</DialogTitle>
+                        <DialogContent>
+                            {locConstants.schemaDesigner.deleteConfirmationContent}
+                        </DialogContent>
+
+                        <DialogActions>
+                            <DialogTrigger disableButtonEnhancement>
+                                <Button
+                                    appearance="primary"
```
Comment (caohai) [inline src/reactviews/pages/SchemaDesigner/graph/SchemaDiagramFlow.tsx:283]: should we make `cancel` primary for both confirmation dialogs?

Comment (caohai) [reply src/reactviews/pages/SchemaDesigner/graph/SchemaDiagramFlow.tsx:283]: Chatted with Aasim offline, the original implementation is consistent with the Fluent guideline. https://react.fluentui.dev/iframe.html?viewMode=docs&id=components-dialog--docs#confirmation

**Review by caohai — APPROVED** [review]
