### PR TITLE
Fix Resize for multiple result sets

### LINKED ISSUE #18111: Multiple dropdowns can be opened in results pane
Repro:
1. Connect to server
2. Run a query that returns several columns (e.g. `select * from sys.objects`)
3. Click a column's dropdown arrow
4. Click several more columns' dropdown arrows

Expected:
* clicking another dropdown arrow dismisses the first one
* clicking an open dropdown's arrow again dismisses it

Reality:
I can open all the dropdowns.  All dismiss when any get cancelled.

image

### LINKED ISSUE #18164: Query result panel not working properly
The query result export options do not appear after running a query for the first time:
image

After running the query for the second time:
image

Also, the export option is also gone after clicking between other tabs (and missing the first time I ran the query):
image

### LINKED ISSUE #18171: Query results set toolbar isn't positioned properly after scrolling
- MSSQL Extension Version: Internal, latest

Steps to Reproduce:

1. Run a query with multiple results sets, some with too many columns to view on screen without scrolling
2. Scroll the resultsets up and down, left and right

Expected: The result set toolbar doesn't stay docked on the right and always visible, like it does with the current result set experience.

Actual: The toolbar moves around and isn't even always visible, see the screenshot.

Image

### PR DESCRIPTION
**Pull request by cssuh**
Fixes resize for multiple result set views

multipleResult

Fixes https://github.com/microsoft/vscode-mssql/issues/18139

Fixes #18111

Fixes #18164

Fixes #18171

### CODE REVIEW

File: src/reactviews/pages/QueryResult/queryResultPane.tsx [hunk 1]
```diff
@@ -109,19 +110,33 @@ export const QueryResultPane = () => {
...
             }
+
             if (gridParent.clientWidth && gridParent.clientHeight) {
-                gridRef.current.resizeGrid(
-                    gridParent.clientWidth,
-                    gridParent.clientHeight -
-                        ribbonRef.current.clientHeight -
-                        5,
-                );
+                //TODO: add case for multiple result grid
```
Comment (Benjin) [inline src/reactviews/pages/QueryResult/queryResultPane.tsx:121]: Can you add a GH issue link to this comment so the TODO doesn't get lost?

File: src/reactviews/pages/QueryResult/queryResultPane.tsx [hunk 2]
```diff
@@ -226,7 +246,7 @@ export const QueryResultPane = () => {
                                 });
                             });
                     }}
-                    ref={gridRef}
+                    ref={(el) => (gridRefs.current[idx] = el!)}
```
Comment (Benjin) [inline src/reactviews/pages/QueryResult/queryResultPane.tsx:249]: what's `el`?  might be worth using a longer name if the abbreviation isn't intuitive.

**Comment by Benjin** [comment]
Can you also add a video to the PR showing that the single result set case mentioned in the bug is also fixed?

File: src/reactviews/pages/QueryResult/queryResultPane.tsx (hunk 1 above)
Comment (cssuh) [reply src/reactviews/pages/QueryResult/queryResultPane.tsx:121]: actually this is fixed, I'll remove it.

File: src/reactviews/pages/QueryResult/queryResultPane.tsx [hunk 3]
```diff
@@ -109,19 +110,33 @@ export const QueryResultPane = () => {
...
-                        5,
-                );
+                //TODO: add case for multiple result grid
+                if (gridRefs.current.length > 1) {
+                    gridRefs.current.forEach((gridRef) => {
+                        gridRef.resizeGrid(
+                            gridParent.clientWidth - ACTIONBAR_WIDTH,
+                            (gridParent.clientHeight -
+                                ribbonRef.current!.clientHeight -
+                                gridRefs.current.length * 5) /
```
[the remark this answers is not in the document]
Comment (cssuh) [reply src/reactviews/pages/QueryResult/queryResultPane.tsx:128]: This fixes the alignment of the grid, probably not the best solution so I will see if I can figure out why each grid is off by 5 pixels.

File: src/reactviews/pages/QueryResult/table/table.ts [hunk 4]
```diff
@@ -26,7 +26,7 @@ function getDefaultOptions<T extends Slick.SlickData>(): Slick.GridOptions<T> {
     } as Slick.GridOptions<T>;
 }
 
-const ACTIONBAR_WIDTH = 36; //px
+export const ACTIONBAR_WIDTH = 36; //px
```
Comment (lewis-sanchez) [inline src/reactviews/pages/QueryResult/table/table.ts:29]: Maybe rename this to ACTIONBAR_WIDTH_PX, so that we don't have to remember that the units for this const is in px.

Comment (lewis-sanchez) [reply src/reactviews/pages/QueryResult/table/table.ts:29]: It also will help to make the const self documenting, so that you don't need to have the `//px` comment

File: src/reactviews/pages/QueryResult/queryResultPane.tsx (hunk 3 above)
[the remark this answers is not in the document]
Comment (Benjin) [reply src/reactviews/pages/QueryResult/queryResultPane.tsx:127]: Good enough for now, just add a comment to the code saying what that's for

**Review by Benjin — APPROVED** [review]

File: src/reactviews/pages/QueryResult/queryResultPane.tsx (hunk 3 above)
[the remark this answers is not in the document]
Comment (lewis-sanchez) [reply src/reactviews/pages/QueryResult/queryResultPane.tsx:127]: Why do we need to multiply by 5, if we're off by 5 px? Wouldn't + 5 make more sense or am I missing something?

File: src/reactviews/pages/QueryResult/queryResultPane.tsx [hunk 5]
```diff
@@ -109,19 +110,32 @@ export const QueryResultPane = () => {
...
+                                gridRefs.current.length,
+                        );
+                    });
+                } else if (gridRefs.current.length === 1) {
+                    gridRefs.current[0].resizeGrid(
+                        gridParent.clientWidth - ACTIONBAR_WIDTH_PX,
+                        gridParent.clientHeight -
+                            ribbonRef.current.clientHeight -
+                            5,
```
[the remark this answers is not in the document]
Comment (lewis-sanchez) [reply src/reactviews/pages/QueryResult/queryResultPane.tsx:136]: Maybe a const would be better, so that we don't have to remember why 5 is being used in the future?

**Review by lewis-sanchez — APPROVED** [review]

**Review by caohai — APPROVED** [review]
