### PR TITLE
Fixing aad connection in schema designer and other misc fixes. 

### LINKED ISSUE #19093: Schema Designer cannot be found in all Database nodes
Steps to Reproduce:

1. In Connection Dialogue, specify the database that you want to connect and hit Connect
2. Observe that you cannot find the "Design Schema (preview)" button for these kind of databases, since it only appears in the Database folder

Schema Designer missing
Image

Schema Designer can be found
Image

Expected behavior:
"Design Schema (preview)" can be found in all Database nodes, including the scenario described above.
**Another scenario** - We should also show this option in the interface if user didn't click "Enable Group by Schema" (I am not able to repro since I enabled Group by Schema before and can't disable anymore)

### LINKED ISSUE #19106: Add support for Azure SQL Database
Schema Designer appears to not support Azure SQL Database. This is what I’ve experienced:

https://github.com/user-attachments/assets/78032341-d3e1-4857-9ce8-df8f87ee067a

Here are some of the errors from the Developer tools console
```
console.ts:137 [Extension Host] Error: The target database schema could not be retrieved. 
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: The target database schema could not be retrieved.  
mainThreadExtensionService.ts:78 [ms-mssql.mssql]The target database schema could not be retrieved. 
```

Let me know if you need me to upload my log file.
cc @yoleichen

### LINKED ISSUE #19109: Computed columns are not included in T-SQL script
Computed columns are not included when the T-SQL script generated by Schema Designer:
Image

@yoleichen

### PR DESCRIPTION
**Pull request by aasimkhan30**
1. Adding schema designer to connection level database in OE. Fixes #19093 
2. Adds publishing option to publish dialog. 
3. Adds support for azure sql dbs Fixes #19106 
4. Adds support for computed columns Fixes #19109

### CODE REVIEW

File: src/reactviews/pages/SchemaDesigner/toolbar/publishChangesDialogButton.tsx [hunk 1]
```diff
@@ -5,331 +5,583 @@
...
+        reportError: undefined,
+        isConfirmationChecked: false,
+        selectedReportId: "",
+        reportTab: "report",
+        publishError: undefined,
+        currentStage: PublishDialogStages.NotStarted,
+    });
 
-    const [selectedReportId, setSelectedReportId] = useState<string>("");
+    // function getReportIcon(state: SchemaDesigner.SchemaDesignerReportTableState) {
```
Comment (lewis-sanchez) [inline src/reactviews/pages/SchemaDesigner/toolbar/publishChangesDialogButton.tsx:77]: What's the commented out code for?

File: src/reactviews/pages/SchemaDesigner/toolbar/publishChangesDialogButton.tsx [hunk 2]
```diff
@@ -5,331 +5,583 @@
...
+                        <MessageBar
+                            intent="warning"
+                            style={{
+                                marginBottom: "10px",
+                                marginTop: "10px",
+                            }}>
+                            {locConstants.schemaDesigner.hasWarnings}
+                        </MessageBar>
+                    )}
+                    {/* <div
```
Comment (lewis-sanchez) [inline src/reactviews/pages/SchemaDesigner/toolbar/publishChangesDialogButton.tsx:337]: Still need this?

**Review by lewis-sanchez — APPROVED** [review]

**Review by caohai — APPROVED** [review]

**Review by laurenastrid1 — APPROVED** [review]
