### PR TITLE
Vscode-mssql bugs fixes for table

### LINKED ISSUE #17198: A11y_mssql for VSCode_Message Window_ScreenReader:Screen reader is announcing the "message" dropdown as collapsed when it is in expanded state and vise versa.
## Actual:
Screen reader is announcing the "message" dropdown as collapsed when it is in expanded state and vise versa.

**Similar issue is observed with Jaws**
**Similar issue is also observed in Select top 1000 Results window_Results and messages window.**

## Expected:
Screen reader should announce the "message" dropdown as expanded when it is in expanded state and collapsed when it is in collapsed state.

**GitHubTags:**#A11yMAS;#A11yTCS;#BM_mssql for VSCode_Jan2022;#mssql for VSCode;#Win32;#FTP;#DesktopApp;#A11ySev2;#AINotInScope;#WCAG1.3.1;#NVDA;#Jaws;#STP;#Element:Dropdown;

## Environment Details:
Application Name: mssql for VSCode
Windows Version: Win11
Screen Reader: NVDA(2021.3), Jaws(2021.2103.174)

## Repro Steps:

1. Open Visual studio code 
2. Tab till extension button and search for "mssql"
3. Tab till install and move to the SQL Server  button
4. Tab till Add Connection Button and insert the valid credentials
5. Right click on the server/database node you want to run the new query on.
6. Press enter “New Query” write any valid query and click on "Execute query button"
7. Message Window will open
8. Run NVDA and tab to the "message" dropdown and check if the NVDA is announcing "message" dropdown as collapsed when it is in expanded state and vise versa.

## User Impact:
Screen reader users will get confused if the screen reader is announcing all the state of dropdown incorrectly

“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

### LINKED ISSUE #17209: A11y_mssql for VSCode_Select top 1000 Results window_Keyboard:When tabbing to table in results section there is an unnecessary focus is moving to the whole section
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:**#A11yMAS;#A11yTCS;#BM_mssql for VSCode_Jan2022;#mssql for VSCode;#Win32;#FTP;#DesktopApp;#A11ySev2;#Keyboard;#AINotInScope;#WCAG2.4.3;#FocusOrder;

## Environment Details:
Application Name: mssql for VSCode
Windows Version: Win11

## Repro Steps:

1. Open Visual studio code 
2. Tab till extension button and search for "mssql"
3. Tab till install and move to the SQL Server  button
4. Tab till Add Connection Button and insert the valid credentials
5. After adding the server move to database expand it -->System database expand-->Master expand-->Tables expand -->System table expand and right click on it and select top 1000 option
6. Select top 1000 window will open 
7. .Select top 1000 window will open tab to Results window 
8. Tab to the results section and check if there is an unnecessary focus is moving to the whole page when tabbing to table in results.

## Actual:
When tabbing to table in results section there is an unnecessary focus is moving to the whole section, which will be difficult to a keyboard user and also screen reader is also not announcing any data will confuse the screen reader users.
## Expected:
When tabbing to table in results section there should not be any unnecessary focus is moving to the whole section, instead the focus should move to the table in results section directly.
## User Impact:
Keyboard users will face difficulty in navigating the page and also screen reader users will get confused.

### PR DESCRIPTION
**Pull request by smartguest**
Fixes #17198

also 

Fixes #17209

The changes here that I made are:

Changing the aria-expanded label of the results/messages header to properly reflect the current state of the collapsed/expanded dropdown. (Previously the state announced by the screen reader was opposite), instead of !resultActive/!messageActive, its now simply resultActive/messageActive

aria-expanded-true-screenshot

The slickgrid is no longer keyboard focusable

### CODE REVIEW

File: src/views/htmlcontent/src/js/components/app.component.ts [hunk 1]
```diff
@@ -40,25 +40,25 @@ export interface IGridDataSet {
 
 // tslint:disable:max-line-length
 const template = `
-<div class="fullsize vertBox">
-    <div *ngIf="dataSets.length > 0" role="button" id="resultspane" tabIndex="0" class="boxRow header collapsible"
+<div class="fullsize vertBox" tabindex="-1">
```
Comment (alanrenmsft) [inline src/views/htmlcontent/src/js/components/app.component.ts:43]: -1 means not keyboard focusable, but programmatically focusable. why do we need to set it as -1 here?

**Comment by alanrenmsft** [comment]
please add description on how will the changes fix the issues. it is not obvious for me.

File: src/views/htmlcontent/src/js/components/app.component.ts (hunk 1 above)
Comment (smartguest) [reply src/views/htmlcontent/src/js/components/app.component.ts:43]: The person specifically requested the tab key to not go to the whole section: https://github.com/microsoft/vscode-mssql/issues/17209 @alanrenmsft, in my findings I found that this was the window for the whole element, I decided to get rid of the keyboard focus because it would allow the user to tab to the slickgrid table directly. (Is there a way to make the entire element itself not focusable at all?)

**Comment by smartguest** [comment]
@alanrenmsft The changes here that I made are changing the aria-expanded label to properly reflect the current state of the collapsed/expanded dropdown.

The tab order is set so that any overall container boxes are not tab focusable (to streamline the navigation for tab users), and to make tabbing go in a more natural order: From results pane header to slick-grid vertbox, to the save/export icons on the right, to the message pane header, and finally scrollable messages.

File: src/views/htmlcontent/src/js/components/app.component.ts (hunk 1 above)
Comment (alanrenmsft) [reply src/views/htmlcontent/src/js/components/app.component.ts:43]: a div is by default not keyboard focusable

File: src/views/htmlcontent/src/js/components/app.component.ts [hunk 2]
```diff
@@ -41,24 +41,24 @@ export interface IGridDataSet {
 // tslint:disable:max-line-length
 const template = `
 <div class="fullsize vertBox">
-    <div *ngIf="dataSets.length > 0" role="button" id="resultspane" tabIndex="0" class="boxRow header collapsible"
+    <div *ngIf="dataSets.length > 0" role="button" id="resultspane" tabIndex="1" class="boxRow header collapsible"
```
Comment (alanrenmsft) [inline src/views/htmlcontent/src/js/components/app.component.ts:44]: we don't usually do this. tab index=0 will make the element keyboard focusable, and the order will be determined by the its position in the DOM tree. please keep this as 0.

File: src/views/htmlcontent/src/js/components/app.component.ts [hunk 3]
```diff
@@ -41,24 +41,24 @@ export interface IGridDataSet {
...
+    <div id="results" *ngIf="renderedDataSets.length > 0" class="results vertBox scrollable"
          (onScroll)="onScroll($event)"
          [scrollEnabled]="scrollEnabled"
          [class.hidden]="!resultActive">
         <div class="boxRow content horzBox slickgrid" *ngFor="let dataSet of renderedDataSets; let i = index"
             [style.max-height]="renderedDataSets.length > 1 ? dataSet.maxHeight + 'px' : 'inherit'"
             [style.min-height]="renderedDataSets.length > 1 ? dataSet.minHeight + 'px' : 'inherit'"
             [style.font-size]="resultsFontSize + 'px'">
-            <slick-grid tabindex="0" #slickgrid id="slickgrid_{{i}}" [columnDefinitions]="dataSet.columnDefinitions"
+            <slick-grid tabindex="2" #slickgrid id="slickgrid_{{i}}" [columnDefinitions]="dataSet.columnDefinitions"
```
Comment (alanrenmsft) [inline src/views/htmlcontent/src/js/components/app.component.ts:61]: remove the tabindex here

File: src/views/htmlcontent/src/js/components/app.component.ts [hunk 4]
```diff
@@ -73,7 +73,7 @@ const template = `
             </slick-grid>
             <span class="boxCol content vertBox">
                 <div class="boxRow content maxHeight" *ngFor="let icon of dataIcons">
-                    <div *ngIf="icon.showCondition()" class="gridIcon">
+                    <div *ngIf="icon.showCondition()" class="gridIcon" tabindex="3">
```
Comment (alanrenmsft) [inline src/views/htmlcontent/src/js/components/app.component.ts:76]: this should not have tabindex, the a tag inside this is focusable by default.

File: src/views/htmlcontent/src/js/components/app.component.ts [hunk 5]
```diff
@@ -85,18 +85,18 @@ const template = `
     </div>
     <context-menu #contextmenu (clickEvent)="handleContextClick($event)"></context-menu>
     <msg-context-menu #messagescontextmenu (clickEvent)="handleMessagesContextClick($event)"></msg-context-menu>
-    <div id="messagepane" role="button" tabIndex="1" class="boxRow header collapsible"
+    <div id="messagepane" role="button" tabIndex="4" class="boxRow header collapsible"
```
Comment (alanrenmsft) [inline src/views/htmlcontent/src/js/components/app.component.ts:88]: change this to 0

File: src/views/htmlcontent/src/js/components/app.component.ts [hunk 6]
```diff
@@ -85,18 +85,18 @@ const template = `
...
+        [attr.aria-expanded]="messageActive"
         (click)="toggleMessagesPane()"
         (keydown)="handleMessagesKeydown($event)"
         style="position: relative">
         <div id="messageResizeHandle" class="resizableHandle"></div>
         <span> {{Constants.messagePaneLabel}} </span>
         <span class="shortCut"> {{messageShortcut}} </span>
     </div>
-    <div id="messages" class="scrollable messages" [class.hidden]="!messageActive"
+    <div id="messages" class="scrollable messages" tabindex="5" [class.hidden]="!messageActive"
```
Comment (alanrenmsft) [inline src/views/htmlcontent/src/js/components/app.component.ts:99]: this shouldn't be keyboard focusable.

**Review by alanrenmsft — APPROVED** [review]

**Comment by alanrenmsft** [comment]
@smartguest I assume you have tested the changes I proposed. right? just want to make sure
