### PR TITLE
Fixing Keyboard accessibility for Query Results grid. 

### LINKED ISSUE #19821: Users are not able to access Sort and Filter functionality present for column headers via keyboard:A11y_MSSQL for VSCode_Connection database_Adding New Query_Keyboard.
"[Check out Accessibility Insights](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-stfe%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458850501301&sdata=mxhokIKNMb22llsjXHLgU3XZibj1Qfx37rpY4PU2sfE%3D&reserved=0)! - Identify accessibility bugs before check-in and make bug fixing faster and easier."
### GitHub Tags:
#A11yTCS;#MSSQL for VSCode;#SH_MSSQLForVSCode_Win32_Jul2025;#DesktopApp;#FTP;#Win11;#A11ySev2;#WCAG1.4.3;#WCAG2.1.1;#A11yMAS;
### Environment Details:
Application: MSSQL for VSCode
Visual studio code version: 1.102.1
OS: Windows 11 Enterprise 24H2
Build: 26100.4652
### Repro Steps: 

1. Launch visual studio code application
2. Sign in with "GitHub" account
3. Tab till "Extension" and press enter
4. Tab till search box and enter "SQL" (mssql) server and install extension
5. Tab till any database and click on "New query" and press enter.
6. write the new query and run the query.
7. The output will be displayed
8. Observe that the users are not able to access Sort and Filter functionality present for column headers via keyboard

### Actual:
Users are not able to access Sort and Filter functionality present for column headers via keyboard
### Expected:
Users should be able to access and operate Sort and Filter controls on column headers using keyboard navigation alone
### User Impact:
Keyboard-only users and those using assistive technologies like screen readers are unable to sort or filter data in tables.
### Attachment:

https://github.com/user-attachments/assets/98509efc-f238-4921-b40c-acfa3d449d42

### PR DESCRIPTION
**Pull request by aasimkhan30**
# Pull Request Template – vscode-mssql

## Description

1. Showing column menu shortcut
image

2. Making command bar in results grid a toolbar so that we can navigate the buttons with arrow keys.
image

3. Adding keyboard shortcuts to context menu
image

4.Adding shortcuts.
   1. Shift + Alt + 0 for sort
   2. Fix tab behavior in grid (tab moves to next element out of grid, where as shift tab moves to previous element before grid)
   3. Shift + space selects entire row.
   4. Shift + F10 opens context menu 
   5. meta + space selects entire column
   6. meta + left arrow moves to first cell of the row.
   7. meta + right arrow moves to the last cell of the row.
   8. F3 Will show column menu. Fixes #19821

## Code Changes Checklist

-   [ ] New or updated **unit tests** added
-   [ ] All existing tests pass (`npm run test`)
-   [ ] Code follows [contributing guidelines](https://github.com/microsoft/vscode-mssql/blob/main/CONTRIBUTING.md)
-   [ ] Telemetry/logging updated if relevant
-   [ ] No regressions or UX breakage

### CODE REVIEW

**Comment by Benjin** [comment]
How'd you end up picking these shortcuts?  IMO, we should generally avoid using `meta` shortcuts since those are typically intended for OS-level features that might conflict.  Like:

`meta + space`: spotlight on macOS
`meta + arrrow`: window-snapping on Windows

I, for one, would find those particular overlaps to be pretty annoying if my VS Code window keeps moving around when I'm trying to move to specific columns, or spotlight keeps opening when I try to select a column.

File: src/reactviews/pages/QueryResult/table/plugins/ColumnMenuPopup.tsx [hunk 1]
```diff
@@ -530,7 +531,17 @@ export const ColumnMenuPopup: React.FC<ColumnMenuPopupProps> = ({
...
-                <Text className={styles.sectionHeading}>Sort</Text>
+                <Text className={styles.sectionHeading}>
+                    {locConstants.queryResult.sort}
+                    <span
+                        style={{
+                            fontSize: "8px",
+                            fontWeight: "100",
+                            marginLeft: "6px",
+                        }}>
+                        (Shift + Alt + O)
```
Comment (Benjin) [inline src/reactviews/pages/QueryResult/table/plugins/ColumnMenuPopup.tsx]: Even though thye're not localized, I think we should keep all keyboard shortcut strings in a central spot (shortcutConstants.ts?).  Since we have different ways to hint at the shortcut, centralizing the strings would be especially nice for traceability, IMO.

File: src/reactviews/common/keys.ts [hunk 2]
```diff
@@ -11,6 +11,54 @@ export enum KeyCode {
...
+    Digit3 = "Digit3",
+    Digit4 = "Digit4",
+    Digit5 = "Digit5",
+    Digit6 = "Digit6",
+    Digit7 = "Digit7",
+    Digit8 = "Digit8",
+    Digit9 = "Digit9",
+    Digit0 = "Digit0",
+    ContextMenu = "ContextMenu",
+    Tab = "Tab",
```
Comment (Benjin) [inline src/reactviews/common/keys.ts:63]: Can you move these up to arrows/esc/enter?  They belong together.

File: src/reactviews/common/utils.ts [hunk 3]
```diff
@@ -136,3 +136,119 @@ export function isMac(): boolean {
...
+    return true;
+}
+
+function getFocusableElements(root: ParentNode = document): HTMLElement[] {
+    return Array.from(root.querySelectorAll<HTMLElement>(FOCUSABLE_SELECTOR)).filter(
+        (el) => !el.hasAttribute("disabled") && isElementVisible(el),
+    );
+}
+
+function getAdjacentFocusableElement(
```
Comment (Benjin) [inline src/reactviews/common/utils.ts:189]: Can you flesh out the docstrings for these util methods?

File: src/reactviews/pages/QueryResult/table/plugins/cellSelectionModel.plugin.ts [hunk 4]
```diff
@@ -592,19 +602,87 @@ export class CellSelectionModel<T extends Slick.SlickData>
     }
 
     private async handleKeyDown(e: KeyboardEvent): Promise<void> {
```
Comment (Benjin) [inline src/reactviews/pages/QueryResult/table/plugins/cellSelectionModel.plugin.ts:604]: This method is getting to be pretty long.  Can you organize it with some helper methods a bit, please?

File: src/reactviews/pages/QueryResult/table/plugins/cellSelectionModel.plugin.ts [hunk 5]
```diff
@@ -592,19 +602,87 @@ export class CellSelectionModel<T extends Slick.SlickData>
...
+            ranges.push(finalRange);
+
+            // Keep the new edge in view
+            const viewRow = dirRow > 0 ? finalRange.toRow : finalRange.fromRow;
+            const viewCell = dirCell > 0 ? finalRange.toCell : finalRange.fromCell;
+            this.grid.scrollRowIntoView(viewRow, false);
+            this.grid.scrollCellIntoView(viewRow, viewCell, false);
+
+            // Commit selection and swallow the event
+            this.setSelectedRanges(ranges);
```
Comment (Benjin) [inline src/reactviews/pages/QueryResult/table/plugins/cellSelectionModel.plugin.ts]: should this also end with a `return`?  Or might there be other handlers that also apply to this event?

File: src/reactviews/pages/QueryResult/table/plugins/GridContextMenu.tsx [hunk 6]
```diff
@@ -58,22 +59,22 @@ export const GridContextMenu: React.FC<GridContextMenuProps> = ({
                 }}>
                 <MenuPopover onClick={(e) => e.stopPropagation()} ref={popoverRef}>
                     <MenuList>
-                        <MenuItem onClick={() => onAction(GridContextMenuAction.SelectAll)}>
+                        <MenuItem
+                            secondaryContent={isMac() ? "⌘A" : "Ctrl+A"}
```
Comment (Benjin) [inline src/reactviews/pages/QueryResult/table/plugins/GridContextMenu.tsx]: more candidates for centralization

**Review by Benjin — APPROVED** [review]
