### PR TITLE
Fix tab switch behavior

### LINKED ISSUE #18276: Wrong grid height when switching between panel tabs
Steps to repro:
1. Run a query with 2 results:
```
select * from sys.objects
go
select * from sys.objects
```
2. switch to `Terminal` then back to `Query Results` tab
Image

This issue goes away when you:
1. Resize
2. Re-run the query
3. Switch to a different editor tab then switch back
4. Switch to `Messages` tab then back to `Results` tab.

### PR DESCRIPTION
**Pull request by cssuh**
Fixes #18276

TODO:

- [x] Cleanup PR
- [x] Fix multiple resize height
- [x] Fix sizing issue with last row

### CODE REVIEW

**Comment by caohai** [comment]
Is there anything special about the height calculation on Windows?

**Comment by cssuh** [comment]
> Is there anything special about the height calculation on Windows?

Updated, it isn't a Windows-related thing

File: src/reactviews/pages/QueryResult/queryResultPane.tsx [hunk 1]
```diff
@@ -144,55 +145,85 @@ export const QueryResultPane = () => {
             return; // Exit if there are no grids to render
         }
 
-        const gridParent = gridParentRef.current;
-        if (!gridParent) {
+        const resultPaneParent = resultPaneParentRef.current;
+        if (!resultPaneParent) {
+            console.log("resultPaneParent null");
```
Comment (Benjin) [inline src/reactviews/pages/QueryResult/queryResultPane.tsx:150]: `console.log()` often means that we should think more about what we want to log and how:
* should it be removed because it was just for development debugging?
* should it instead be `console.warn()`, if we want users to be able to find it if they need to file a bug?
* is this an error that we should be emitting telemetry for?

Comment (Benjin) [reply src/reactviews/pages/QueryResult/queryResultPane.tsx:150]: Same for other instances of `console.log`

Comment (cssuh) [reply src/reactviews/pages/QueryResult/queryResultPane.tsx]: I removed these log statements, they were just for debugging purposes

File: src/reactviews/pages/QueryResult/resultGrid.tsx [hunk 2]
```diff
@@ -81,7 +82,18 @@ const ResultGrid = forwardRef<ResultGridHandle, ResultGridProps>(
             }
             setRefreshKey((prev) => prev + 1);
         };
+        // const gridParent = props.gridParentRef?.current;
```
Comment (caohai) [inline src/reactviews/pages/QueryResult/resultGrid.tsx:85]: do we still need this?

**Review by caohai — APPROVED** [review]

File: src/reactviews/pages/QueryResult/resultGrid.tsx (hunk 2 above)
Comment (cssuh) [reply src/reactviews/pages/QueryResult/resultGrid.tsx]: no, I'll remove it

**Review by kburtram — APPROVED** [review]
