### PR TITLE
Using Ids to match is same connection profile.

### LINKED ISSUE #19091: Duplicate connection entry created when connecting to saved connection
Steps to Reproduce:

*  No definitive reproduction steps found yet.

*  Occurred during normal usage, specifically when connecting to a saved connection.

*  STS was under debug mode at the time. Observed a recoverable SQL client exception in logs, but unclear if related.

Expected Behavior: Connecting to an existing saved connection does not create duplicate connection entries.

Actual Behavior: A duplicate connection entry appeared. Notably, the duplicated connection included the server version info, which wasn't observed in previous duplicate connection bugs. (Uncertain if displaying server version is new behavior or simply unnoticed previously.)

Image

### PR DESCRIPTION
**Pull request by aasimkhan30**
Fixes #19091

This PR resolves an issue where connections created using a connection string and the old connection prompt flow were not being correctly reconciled in the Object Explorer (OE).

Initially, we stored the disconnected node's profile like this:
```json
{
  "connectionString": "{lookup-key}"
}
```

But once the connection was established, the node's profile changed to:
```json
{
  "connectionString": "{actual-connection}"
}
```

This mismatch caused OE to treat them as different connections, so instead of replacing the disconnected node with the connected one, it just added a new connected node leading to duplicates.

This PR ensures the profiles match correctly so OE can update the existing node instead of duplicating it.

### CODE REVIEW

**Review by lewis-sanchez — APPROVED** [review]

File: src/models/utils.ts [hunk 1]
```diff
@@ -308,6 +312,13 @@ export function isSameConnectionInfo(
     conn: IConnectionInfo,
     expectedConn: IConnectionInfo,
 ): boolean {
+    // If connection info has an id, use that to compare connections
+    const connId = (<IConnectionProfile>conn).id;
```
Comment (Benjin) [inline src/models/utils.ts:316]: Nit: good practice to use `as` instead of `<>` for casting just due to JSX/TSX portability.

**Review by Benjin — APPROVED** [review]

**Review by Benjin — APPROVED** [review]

**Review by lewis-sanchez — APPROVED** [review]
