### PR TITLE
Fix for Publish Project to Docker container fails with "port already allocated" and "Login failed for SA"

### LINKED ISSUE #21913: [Bug]: Publish Project to Docker container fails with "port already allocated" and "Login failed for SA"
### Description

Publishing a project to a new local Docker container fails with HTTP 500 "port is already allocated" when the user-entered port is in use by a stopped container
Even when the port is free, "Login failed for user 'SA'" occurs because the publish flow connects immediately after checkContainer with no delay, while the deployment UI works because the user manually clicks "Connect" which adds a natural gap

### Steps to Reproduce

1. Create/open a sql project
2. Open publish dialog
3. Select publish to local container target option
4. Fill out the details and publish it.
5. Publish is failing with login failed for user SA

Image
Image

### Affected Area

- [ ] Connection dialog (SQL Server | Azure browse/Fabric browse)
- [ ] Query editor
- [ ] Query results panel
- [ ] Object Explorer
- [ ] GitHub Copilot integration
- [ ] Preview/Edit data
- [ ] Table Designer
- [ ] Schema Designer
- [ ] Schema Compare
- [ ] Local SQL Server Container provisioning
- [ ] SQL database in Fabric provisioning
- [ ] DACPAC/BACPAC export/import
- [ ] SQL Database projects
- [ ] Query Plan Visualizer
- [ ] Other (please describe below)

### If you selected "Other", please describe the affected area

_No response_

### Environment Information

- VsCode: 1.42.0
- SqlProj: 1.5.9

### Confirmation

- [x] I have searched existing issues and couldn't find a match
- [x] I want to work on this issue

### PR DESCRIPTION
**Pull request by ssreerama**
## Description

Issue founf while testing
- The publish flow is fully automated. It calls createObjectExplorerSession immediately after checkContaine returns success, 
- SQL Server logs "ready for client connections" slightly before SA authentication is fully initialized — so the first connection attempt gets "Login failed for user 'SA'"
- Added a retry loop, with a delay before each attempt
- The first delay gives SQL Server time to finish SA initialization; subsequent delays back off on transient failures
- Also, added a port already allocated user error while entering the port number in the field
- Tests to validate the scenario

 ## Code Changes Checklist

- [ ] New or updated **unit tests** added
- [ ] All existing tests pass (`npm run test`)
- [ ] Code follows [contributing guidelines](https://github.com/microsoft/vscode-mssql/blob/main/CONTRIBUTING.md)
- [ ] Telemetry/logging updated if relevant
- [ ] No regressions or UX breakage

## Reviewers: [Please read our reviewer guidelines](https://github.com/microsoft/vscode-mssql/blob/main/.github/REVIEW_GUIDELINES.md)

Before: Publish fails after container creation with login error:
image

After: 
Apr_Test_ContainerFailure

port number default to non-allocated port after 1433
image

### CODE REVIEW

**Comment by aasimkhan30** [comment]
Please populate the field with the first available port

**Comment by ssreerama** [comment]
working on copilot suggestions, some seems applicable.

File: extensions/mssql/src/publishProject/publishProjectWebViewController.ts [hunk 1]
```diff
@@ -1650,6 +1677,42 @@ export class PublishProjectWebViewController extends FormWebviewController<
...
+            isPortField &&
+            this.state.formState.publishTarget === PublishTarget.LocalContainer &&
+            updateValidation
+        ) {
+            const portComponent = this.state.formComponents[PublishFormFields.ContainerPort];
+            const portStr = String(this.state.formState.containerPort ?? "").trim();
+            const portNum = Number(portStr);
+            // Only run availability check if the value is already a valid port number
+            if (portComponent && !isNaN(portNum) && portNum > 0) {
+                const availablePort = await dockerUtils.findAvailablePort(portNum);
```
Comment (Benjin) [inline extensions/mssql/src/publishProject/publishProjectWebViewController.ts:1706]: This is a good check to have, but why not default the port number to the first available port above the default (1433)?  Seems silly to have the form default be a value that we know isn't valid.

File: extensions/mssql/src/constants/locConstants.ts [hunk 2]
```diff
@@ -1767,6 +1767,8 @@ export class PublishProject {
     public static CreatingSqlServerContainer = l10n.t("Creating SQL Server container...");
     // Validation messages
     public static InvalidPortMessage = l10n.t("Port must be a number between 1 and 65535");
+    public static PortAlreadyInUse = (port: number) =>
```
Comment (Benjin) [inline extensions/mssql/src/constants/locConstants.ts:1770]: Include placeholder comments so this can be localized correctly, example:

```
        l10n.t({
            message:
                "Profile loaded, but the connection could not be automatically established. Please create a connection to {0} then try again.",
            args: [serverName],
            comment: ["{0} is the server name"],
        });
```

File: extensions/mssql/src/publishProject/publishProjectWebViewController.ts (hunk 1 above)
Comment (ssreerama) [reply extensions/mssql/src/publishProject/publishProjectWebViewController.ts:1706]: true, the original ask was to default to 1433, but since it is not available, will default to the available port number from 1433 default.

File: extensions/mssql/src/publishProject/publishProjectWebViewController.ts [hunk 3]
```diff
@@ -491,51 +492,77 @@ export class PublishProjectWebViewController extends FormWebviewController<
...
+        const maxConnectionAttempts = constants.containerConnectionMaxAttempts;
+        const connectionRetryDelayMs = constants.containerConnectionRetryDelayMs;
+        let lastConnectionError: string | undefined;
 
-            // Open in Object Explorer (this also establishes the connection)
-            await this._mainController.createObjectExplorerSession(savedProfile);
+        for (let attempt = 1; attempt <= maxConnectionAttempts; attempt++) {
+            // Wait before each attempt: the first wait lets SQL Server finish auth
+            // initialisation; subsequent waits back off after a transient failure.
+            await new Promise((resolve) => setTimeout(resolve, connectionRetryDelayMs));
```
[the remark this answers is not in the document]
Comment (Benjin) [reply extensions/mssql/src/publishProject/publishProjectWebViewController.ts]: This is correct; is it a fixed retry wait, or an increasing backoff (e.g. doubling wait time after each failure.  2^n for n=0..3 would be fine)

**Review by Benjin — APPROVED** [review]
