### PR TITLE
[Port] use experimental feature flag with edit data

### LINKED ISSUE #20538: [Bug]: Use Enable Experimental Feature flag with Edit Data
### Description

The Edit Data feature is currently using the enable rich experiences flag, but it should be using the enable experimental feature flag instead.

### Steps to Reproduce

N/A

### Affected Area

- [ ] Connection dialog (SQL Server | Azure browse/Fabric browse)
- [ ] Query results panel
- [ ] Query editor
- [ ] Object Explorer
- [ ] Table Designer
- [ ] Schema Compare
- [ ] Schema Designer
- [ ] Local SQL Server Container provisioning
- [ ] SQL database in Fabric provisioning
- [ ] GitHub Copilot integration
- [ ] Query Plan Visualizer
- [x] Other (please describe below)

### If you selected "Other", please describe the affected area

Edit Data

### Environment Information

N/A

### Confirmation

- [x] I have searched existing issues and couldn't find a match
- [ ] I want to work on this issue

### PR DESCRIPTION
**Pull request by lewis-sanchez**
# Pull Request Template – vscode-mssql

## Description

This PR closes #20538 

Original PR that was merged into main: https://github.com/microsoft/vscode-mssql/pull/20535

_Provide a clear, concise summary of the changes in this PR. What problem does it solve? Why is it needed? Link any related issues using [issue closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)._

## Code Changes Checklist

-   [x] New or updated **unit tests** added
-   [x] All existing tests pass (`npm run test`)
-   [x] Code follows [contributing guidelines](https://github.com/microsoft/vscode-mssql/blob/main/CONTRIBUTING.md)
-   [x] Telemetry/logging updated if relevant
-   [x] No regressions or UX breakage

### CODE REVIEW

**Review by kburtram — APPROVED** [review]
Looks good.  Thanks Lewis!

File: src/objectExplorer/nodes/treeNodeInfo.ts [hunk 1]
```diff
@@ -73,7 +73,9 @@ export class TreeNodeInfo extends vscode.TreeItem implements ITreeNodeInfo {
         // Add command for table nodes to handle double-click
         if (this._nodeType === "Table") {
             const config = vscode.workspace.getConfiguration("mssql");
-            const enableRichExperiences = config.get<boolean>("enableRichExperiences", true);
+            const enableRichExperiences = config.get<boolean>(
```
Comment (kburtram) [inline src/objectExplorer/nodes/treeNodeInfo.ts:76]: Maybe it would be better rename the variable since it's a different config now.  But not necessary.
