### PR TITLE
Add min size & fix resize behavior

### LINKED ISSUE #18248: Result sets have no minimum vertical size when displayed in query results pane
Repro: run a query with 10+ result sets, e.g.

```
select * from sys.objects
select * from sys.objects
select * from sys.objects
select * from sys.objects
select * from sys.objects
select * from sys.objects
select * from sys.objects
select * from sys.objects
select * from sys.objects
select * from sys.objects
select * from sys.objects
select * from sys.objects
select * from sys.objects
select * from sys.objects
select * from sys.objects
select * from sys.objects
select * from sys.objects
select * from sys.objects
select * from sys.objects
```

Expected:
query pane is still usable.  each result set has a minimum height (that's at least the size of the sidebar buttons), and a scrollbar appears to scroll to see the overflow

Reality:
help.
Image

### PR DESCRIPTION
**Pull request by cssuh**
Adds a min size to query results grids & fixes resize behavior

Fixes #18248

minSize

### CODE REVIEW

File: src/reactviews/pages/QueryResult/queryResultPane.tsx [hunk 1]
```diff
@@ -100,6 +100,15 @@ const useStyles = makeStyles({
     },
 });
 
+const MIN_GRID_HEIGHT = 273; // Minimum height for a grid
```
Comment (caohai) [inline src/reactviews/pages/QueryResult/queryResultPane.tsx:103]: Is this a random pick or did we use the same number in ADS?

Comment (cssuh) [reply src/reactviews/pages/QueryResult/queryResultPane.tsx:103]: Using the same number as ADS

File: src/reactviews/pages/QueryResult/queryResultPane.tsx [hunk 2]
```diff
@@ -201,16 +230,7 @@ export const QueryResultPane = () => {
...
         const divId = `grid-parent-${batchId}-${resultId}`;
         return (
-            <div
-                id={divId}
-                className={classes.queryResultContainer}
-                style={{
-                    height:
-                        totalResultCount === 1
-                            ? "100%"
-                            : (100 / totalResultCount).toString() + "%",
```
Comment (caohai) [inline src/reactviews/pages/QueryResult/queryResultPane.tsx:211]: You can remove totalResultCount parameter since it's no longer used.
image

**Comment by caohai** [comment]
If I run a query with 2 result sets then run a single result set query in the same editor, the single result set doesn't take the entire space 
image

**Comment by cssuh** [comment]
> If I run a query with 2 result sets then run a single result set query in the same editor, the single result set doesn't take the entire space image

fixed in latest update

**Review by caohai — APPROVED** [review]
