### PR TITLE
Fix AutoRest code generation failing with spawn errors on Windows

### LINKED ISSUE #21916: [Bug]: Generate SQL PRoj from OpenAPI/Swaggers fails
### Description

Using the preview option "Generate SQL Project from OPENAPI/Swagger spec" should create the sqlproj from the json file, but instead it fials with the eroor 

"Generating project via AutoRest failed.  Check output pane for more details. Error: spawn autorest ENOENT"

### Steps to Reproduce

1. Create project using "Generate SQL Project from OPENAPI/Swagger spec" preview option
2. Use any json file to create a project
3. Observe failure message with autorest.

### Affected Area

- [ ] Connection dialog (SQL Server | Azure browse/Fabric browse)
- [ ] Query editor
- [ ] Query results panel
- [ ] Object Explorer
- [ ] GitHub Copilot integration
- [ ] Preview/Edit data
- [ ] Table Designer
- [ ] Schema Designer
- [ ] Schema Compare
- [ ] Local SQL Server Container provisioning
- [ ] SQL database in Fabric provisioning
- [ ] DACPAC/BACPAC export/import
- [x] SQL Database projects
- [ ] Query Plan Visualizer
- [ ] Other (please describe below)

### If you selected "Other", please describe the affected area

_No response_

### Environment Information

- Vscode-mssql - 1.42
- SqlProjeccts - 1.5.9

### Confirmation

- [x] I have searched existing issues and couldn't find a match
- [x] I want to work on this issue

### PR DESCRIPTION
**Pull request by ssreerama**
## Description

PR #21570 changed spawn to use shell: false (for security). But on Windows, autorest and npx install as .cmd files (e.g. autorest.cmd). With shell: false, the OS can't find or execute .cmd files directly → ENOENT crash.

What we fixed:
- Resolve the full path, use which to find where autorest.cmd / npx.cmd actually lives on disk (instead of just passing the bare name "autorest")
- Route .cmd through cmd.exe — since shell: false can't run .cmd files directly, we wrap it as cmd.exe /d /c C:\...\autorest.cmd so Windows can execute it properly

## Code Changes Checklist

- [ ] New or updated **unit tests** added
- [ ] All existing tests pass (`npm run test`)
- [ ] Code follows [contributing guidelines](https://github.com/microsoft/vscode-mssql/blob/main/CONTRIBUTING.md)
- [ ] Telemetry/logging updated if relevant
- [ ] No regressions or UX breakage

## Reviewers: [Please read our reviewer guidelines](https://github.com/microsoft/vscode-mssql/blob/main/.github/REVIEW_GUIDELINES.md)

Before FiX:
Apr_Test_AutoRest_Before

After Fix:
Apr_Test_AutoRest_After

### CODE REVIEW

**Review by Benjin — CHANGES_REQUESTED** [review]
This is a lot of changed code, so I want to understand this better.  You mentioned something about a .cmd over chat?

* What changed between the last release and this one?
* Was the change in our code or something to do with how NPM operates?

File: extensions/sql-database-projects/src/common/utils.ts [hunk 1]
```diff
@@ -475,6 +475,18 @@ export function timeConversion(duration: number): string {
...
+/**
+ * Returns the fully resolved path of a command, or undefined if not found.
+ */
+export async function resolveCommandPath(command: string): Promise<string | undefined> {
+    try {
+        const found = await which(command);
+        return found || undefined;
+    } catch {
+        return undefined;
+    }
```
[the remark this answers is not in the document]
Comment (Benjin) [reply extensions/sql-database-projects/src/common/utils.ts:487]: We should upgrade `detectCommandInstallation()` to return to the path (if found) or undefined (if not found) instead of true/false

File: extensions/sql-database-projects/src/tools/autorestHelper.ts [hunk 2]
```diff
@@ -14,6 +14,20 @@ const autorestPackageName = "autorest-sql-testing"; // name of AutoRest.Sql pack
 const nodejsDoNotAskAgainKey = "nodejsDoNotAsk";
 const autorestSqlVersionKey = "autorestSqlVersion";
 
+/**
+ * On Windows, .cmd/.bat files cannot be executed directly by spawn(shell:false).
+ * They must be routed through cmd.exe /c.
+ */
+function wrapCmdIfNeeded(resolvedPath: string): { executable: string; prefixArgs: string[] } {
```
Comment (Benjin) [inline extensions/sql-database-projects/src/tools/autorestHelper.ts]: can you make this more generic to also handle .ps1?

File: extensions/sql-database-projects/src/tools/autorestHelper.ts [hunk 3]
```diff
@@ -14,6 +14,20 @@ const autorestPackageName = "autorest-sql-testing"; // name of AutoRest.Sql pack
 const nodejsDoNotAskAgainKey = "nodejsDoNotAsk";
 const autorestSqlVersionKey = "autorestSqlVersion";
 
+/**
+ * On Windows, .cmd/.bat files cannot be executed directly by spawn(shell:false).
+ * They must be routed through cmd.exe /c.
+ */
+function wrapCmdIfNeeded(resolvedPath: string): { executable: string; prefixArgs: string[] } {
+    if (process.platform === "win32" && /\.(cmd|bat)$/i.test(resolvedPath)) {
```
Comment (Benjin) [inline extensions/sql-database-projects/src/tools/autorestHelper.ts]: Does this need to be a regex?  Can it instead be `resolvedPath.endsWith(cmd|bat|ps1)`

Comment (Benjin) [reply extensions/sql-database-projects/src/tools/autorestHelper.ts]: if `ps1`, then the command should be `pwsh.exe`

File: extensions/sql-database-projects/src/tools/autorestHelper.ts [hunk 4]
```diff
@@ -37,15 +51,21 @@ export class AutorestHelper extends ShellExecutionHelper {
...
-        if (await utils.detectCommandInstallation(autorestCommand)) {
-            return autorestCommand;
-        } else if (await utils.detectCommandInstallation(npxCommand)) {
+        const resolvedAutorest = await utils.resolveCommandPath(autorestCommand);
+        if (resolvedAutorest) {
+            return wrapCmdIfNeeded(resolvedAutorest);
+        }
+
+        const resolvedNpx = await utils.resolveCommandPath(npxCommand);
+        if (resolvedNpx) {
```
Comment (Benjin) [inline extensions/sql-database-projects/src/tools/autorestHelper.ts:99]: leave a blank line before logic blocks

File: extensions/sql-database-projects/src/tools/autorestHelper.ts [hunk 5]
```diff
@@ -55,11 +75,19 @@ export class AutorestHelper extends ShellExecutionHelper {
...
             if (response === constants.installGlobally) {
                 this._outputChannel.appendLine(constants.userSelectionInstallGlobally);
-                await this.runStreamedCommand("npm", ["install", "autorest", "-g"]);
-                return autorestCommand;
+                const resolvedNpm = await utils.resolveCommandPath("npm");
+                const { executable: npmExe, prefixArgs: npmArgs } = resolvedNpm
+                    ? wrapCmdIfNeeded(resolvedNpm)
+                    : { executable: "npm", prefixArgs: [] };
+                await this.runStreamedCommand(npmExe, [...npmArgs, "install", "autorest", "-g"]);
+                const newResolved = await utils.resolveCommandPath(autorestCommand);
```
Comment (Benjin) [inline extensions/sql-database-projects/src/tools/autorestHelper.ts]: resolvedAutorest

File: extensions/sql-database-projects/src/tools/autorestHelper.ts [hunk 6]
```diff
@@ -88,9 +116,9 @@ export class AutorestHelper extends ShellExecutionHelper {
             if (
                 vscode.workspace.getConfiguration(DBProjectConfigurationKey)[
                     nodejsDoNotAskAgainKey
-                ] !== true
+                ] === true
```
Comment (Benjin) [inline extensions/sql-database-projects/src/tools/autorestHelper.ts]: Revert

File: extensions/sql-database-projects/test/autorestHelper.test.ts [hunk 7]
```diff
@@ -33,9 +33,9 @@ suite("Autorest tests", function (): void {
         sandbox.stub(window, "showInformationMessage").returns(<any>Promise.resolve(runViaNpx)); // stub a selection in case test runner doesn't have autorest installed
 
         const autorestHelper = new AutorestHelper(testContext.outputChannel);
-        const executable = await autorestHelper.detectInstallation();
+        const installation = await autorestHelper.detectInstallation();
         expect(
-            executable === "autorest" || executable === "npx autorest",
+            installation !== undefined,
```
Comment (Benjin) [inline extensions/sql-database-projects/test/autorestHelper.test.ts]: installation includes string "autorest"

File: extensions/sql-database-projects/src/tools/autorestHelper.ts [hunk 8]
```diff
@@ -14,6 +14,20 @@ const autorestPackageName = "autorest-sql-testing"; // name of AutoRest.Sql pack
 const nodejsDoNotAskAgainKey = "nodejsDoNotAsk";
 const autorestSqlVersionKey = "autorestSqlVersion";
 
+/**
+ * On Windows, .cmd/.bat files cannot be executed directly by spawn(shell:false).
```
Comment (Benjin) [inline extensions/sql-database-projects/src/tools/autorestHelper.ts]: Can we update this docstring to mention that `which` will return an executable path that may contain .cmd or .ps1 depending on environment

File: extensions/sql-database-projects/src/common/utils.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (ssreerama) [reply extensions/sql-database-projects/src/common/utils.ts:487]: actually detectCommandInstallation is a dead code have no references except tests, removed and updated the test to validate the resolveCommandPath.

File: extensions/sql-database-projects/src/tools/autorestHelper.ts (hunk 3 above)
Comment (ssreerama) [reply extensions/sql-database-projects/src/tools/autorestHelper.ts]: done!

File: extensions/sql-database-projects/src/tools/autorestHelper.ts (hunk 4 above)
Comment (ssreerama) [reply extensions/sql-database-projects/src/tools/autorestHelper.ts:99]: followed the pattern, thanks :)

File: extensions/sql-database-projects/test/autorestHelper.test.ts (hunk 7 above)
Comment (ssreerama) [reply extensions/sql-database-projects/test/autorestHelper.test.ts]: update the test to include "autorest"

File: extensions/sql-database-projects/src/tools/autorestHelper.ts (hunk 8 above)
Comment (ssreerama) [reply extensions/sql-database-projects/src/tools/autorestHelper.ts]: Done!

File: extensions/sql-database-projects/src/tools/autorestHelper.ts (hunk 2 above)
Comment (ssreerama) [reply extensions/sql-database-projects/src/tools/autorestHelper.ts]: done

**Review by Benjin — DISMISSED** [review]

**Review by Benjin — APPROVED** [review]
