### PR TITLE
Fixing telemetry event for expand and fixing clear all in filters

### LINKED ISSUE #18572: Clearing filters from filter dialog doesn't clear filters..
- MSSQL Extension Version:
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Apply OE filters to a node.

Image

2. Open filter dialog and click clear all and submit.

Image

3. Filters are not cleared. 

Image

### PR DESCRIPTION
**Pull request by aasimkhan30**
This PR fixes #18572 
1. This PR fixes the clear all button in filter dialog.
2. It makes sure that we are setting up the parent node to expand result map even when we are refreshing the node. Previously this wasn't set so when we tried to access parent node in expand results due to a refresh, we were getting undefined error causing #18052
3. Additionally, this PR updates the telemetry event for expand operations to include the node's subtype instead of the type. Subtypes provide more detailed information—for example, the "Tables" and "Views" folders are both of type "Folder," but their subtypes are "Tables" and "Views," respectively.

### CODE REVIEW

File: src/objectExplorer/objectExplorerService.ts [hunk 1]
```diff
@@ -956,6 +956,7 @@ export class ObjectExplorerService {
             RefreshRequest.type,
             refreshParams,
         );
+        this._expandParamsToTreeNodeInfoMap.set(refreshParams, node);
```
Comment (Benjin) [inline src/objectExplorer/objectExplorerService.ts:959]: So reverting the original "fix" and this like is the proper fix instead?

**Review by Benjin — APPROVED** [review]

File: src/objectExplorer/objectExplorerService.ts (hunk 1 above)
Comment (aasimkhan30) [reply src/objectExplorer/objectExplorerService.ts:959]: Yup, this is the proper fix for the issue.

**Comment by Benjin** [comment]
Approved by Ken via shiproom chat
